name: Pocket Playlist Generator

on:
  schedule:
    - cron: '0 */3 * * *' # Run every 3 hours
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:          # Give permission to write files
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Pocket Script
        run: python create_pocket_playlist.py

      - name: Force Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add pocket_playlist.m3u
          git commit -m "Auto-update Playlist" || echo "No changes to commit"
          git push --force origin main
